properties:
  resources:
    - resource: PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        PowerLauncher:        
          Enabled: true
          OpenPowerLauncher: "Ctrl+Space"
          UseCentralizedKeyboardHook: true
          SearchQueryTuningEnabled: true
          IgnoreHotkeysInFullscreen: false
          GenerateThumbnailsFromFiles: false
          TabSelectsContextButtons: true
          Position: "Focus"
          Plugins:
            - Name: "Everything"
              Disabled: false
              ActionKeyword: "?"
  configurationVersion: 0.2.0
