properties:
  resources:
    - resource: PowerToysConfigure
      directives:
        description: Configure PowerToys Everything plugin
      settings:
        PowerLauncher:        
          Enabled: true
          OpenPowerLauncher: "Ctrl+Space"
          UseCentralizedKeyboardHook: true
          SearchQueryTuningEnabled: true
          IgnoreHotkeysInFullscreen: false
          GenerateThumbnailsFromFiles: false
          TabSelectsContextButtons: true
          Position: "Focus"
          Everything:
            Enabled: true
            ActivationMethod: "?"
  configurationVersion: 0.2.0
