properties:
  resources:
    - resource: PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        FancyZones:
          Enabled: true
          FancyzonesShowZoneNumber: false
          FancyzonesAppLastZoneMoveWindows: false
          FancyZonesEditorHotkey: "Win+Shift+F"
        FindMyMouse:
          Enabled: true
          ActivationMethod: 2
        Peek:
          Enabled: true
          ActivationShortcut: "Alt+Space"
          CloseAfterLosingFocus: true
        AlwaysOnTop:
          Enabled: true
          Hotkey: "Win+A"
          FrameThickness: 4
          FrameOpacity: 70
        RegistryPreview:
          Enabled: false
        PowerLauncher:
          Enabled: true
          OpenPowerLauncher: "Ctrl+Space"
          UseCentralizedKeyboardHook: true
          SearchQueryTuningEnabled: true
          IgnoreHotkeysInFullscreen: false
          GenerateThumbnailsFromFiles: false
          TabSelectsContextButtons: true
          Position: "Focus"
          Plugins:
            - Name: "Calculator"
              Disabled: false
            - Name: "Folder"
              Disabled: false
            - Name: "Program"
              Disabled: false
              IsGlobal: true
            - Name: "Registry Plugin"
              Disabled: true
            - Name: "Service"
              Disabled: false
            - Name: "Shell"
              Disabled: false
            - Name: "Windows System Commands"
              Disabled: false
            - Name: "URI Handler"
              Disabled: false
            - Name: "Web Search"
              Disabled: false
            - Name: "Windows settings"
              Disabled: false
              ActionKeyword: ","
              IsGlobal: false
            - Name: "History"
              Disabled: true
            - Name: "Windows Search"
              Disabled: true
            - Name: "OneNote"
              Disabled: true
            - Name: "PowerToys"
              Disabled: true
            - Name: "Unit Converter"
              Disabled: true
            - Name: "Value Generator"
              Disabled: true
            - Name: "Visual Studio Code Workspaces"
              Disabled: true
            - Name: "Windows Terminal"
              Disabled: true
            - Name: "Window Walker"
              Disabled: true
        ColorPicker:
          Enabled: true
          ActivationShortcut: "Win+C"
        PowerRename:
          Enabled: false
          MRUEnabled: true
          MaxMRUSize: 5
          ExtendedContextMenuOnly: true
          UseBoostLib: true
        ImageResizer:
          Enabled: true
        Awake:
          Enabled: true
        CropAndLock:
          Enabled: false
        EnvironmentVariables:
          Enabled: false
        FileLocksmith:
          Enabled: false
        MouseHighlighter:
          Enabled: false
        MouseJump:
          Enabled: false
        MousePointerCrosshairs:
          Enabled: false
        MouseWithoutBorders:
          Enabled: false
        PowerAccent:
          Enabled: false
        MeasureTool:
          Enabled: false
        Hosts:
          Enabled: false
        PowerOcr:
          Enabled: false
        ShortcutGuide:
          Enabled: false
        VideoConference:
          Enabled: false
        PowerPreview:
          EnableSvgPreview: false
          EnableSvgThumbnail: true
          EnableMdPreview: false
          EnableMonacoPreview: false
          EnablePdfPreview: false
          EnablePdfThumbnail: true
          EnableGcodePreview: false
          EnableGcodeThumbnail: true
          EnableStlThumbnail: true
          EnableQoiPreview: false
          EnableQoiThumbnail: true
  configurationVersion: 0.2.0
